### ISSUE TITLE
Ability to switch back to main keyboard

### ISSUE THREAD

**Issue by DaBaldEagul** [quicksc0p3r/discordtimestampinserter#3]
As it is now, I am unable to switch back to my main keyboard from this input method. Most keyboards allow you to change this from the spacebar, but that's not possible in this case. 

A button that prompts all available input methods would be highly appreciated.

**Comment by quicksc0p3r** [comment]
I will consider implementing this, but for the time being consider using your device's built-in keyboard switching functionality.
![Screenshot_2024-06-06-16-30-51-313_com android chrome-edit](https://github.com/quicksc0p3r/discordtimestampinserter/assets/80166934/729d6244-7abc-48b9-be68-85c80030b66e)

**Comment by quicksc0p3r** [comment]
This feature has been implemented and is now available as part of release 1.0.1.
